### PR TITLE
Support no-std

### PR DESCRIPTION
**Pull request by nickmertin**
Add support for `no-std` builds.

### CODE REVIEW

**Review by twmb — COMMENTED** [review]
Looks good. Do you know if this crate still needs nightly? That could probably be removed at this point.

**Comment by nickmertin** [comment]
It compiles fine on stable 1.65.0 for me.

**Comment by nickmertin** [comment]
I cannot get the current master branch to compile with the `nightly` feature enabled on the latest nightly (2022-11-22), however.

```
warning: the feature `specialization` is incomplete and may not be safe to use and/or cause compiler crashes
 --> src/lib.rs:1:42
  |
1 | #![cfg_attr(feature = "nightly", feature(specialization))]
  |                                          ^^^^^^^^^^^^^^
  |
  = note: see issue #31844 <https://github.com/rust-lang/rust/issues/31844> for more information
  = help: consider using `min_specialization` instead, which is more stable and complete
  = note: `#[warn(incomplete_features)]` on by default

error[E0599]: the method `copy` exists for mutable reference `&mut [T]`, but its trait bounds were not satisfied
   --> src/lib.rs:103:13
    |
103 |         dst.copy(src)
    |             ^^^^ method cannot be called on `&mut [T]` due to unsatisfied trait bounds
    |
note: trait bound `[T]: Cpy` was not satisfied
   --> src/lib.rs:50:1
    |
50  | default impl<T> Cpy<[T]> for [T]
    | ^^^^^^^^^^^^^^^^--------^^^^^---
    | |
    | unsatisfied trait bound introduced here
    = help: items from traits can only be used if the trait is implemented and in scope
note: `Cpy` defines an item `copy`, perhaps you need to implement it
   --> src/lib.rs:42:1
    |
42  | trait Cpy<T = Self>
    | ^^^^^^^^^^^^^^^^^^^
```

**Comment by nickmertin** [comment]
Are there any changes you'd like to see before merging?

**Comment by twmb** [comment]
If it's alright, removing everything related to nightly / specialization. Also, I'll need to re-setup rust and figure out how to upload this crate (I think I actually only need to setup cargo)--I'll need to find a small chunk of time for that on my current todo list.

**Comment by twmb** [comment]
thanks, will merge soon and try to upload at some point

**Comment by nickmertin** [comment]
Just wanted to check if there is any update on this, or if there's anything I can do to help land it.

**Comment by twmb** [comment]
lgtm now, I'll have time to re-set up my Rust environment starting next week. Was on work trip, then a small vacation.

**Comment by twmb** [comment]
Wow, publishing this crate was easy. Sorry for the delay!

**Comment by nickmertin** [comment]
No problem, thanks for publishing the update!
